# Generated by Django 5.1.1 on 2024-09-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
    ]
